### ISSUE TITLE
Contact type missing 'city'

### ISSUE THREAD

**Issue by brycelund** [flexbase-eng/postgrid-node-client#11]
The docs show the property `city` included in a `Contact`, however the typescript typings don't include city and throws an error when supplied. Is this a mistake or did the API change?

```
export interface Contact {
    id: string;
    object: string;
    live: boolean;
    description?: string;
    addressLine1?: string;
    addressLine2?: string;
    provinceOrState?: string;
    postalOrZip?: string;
    country?: string;
    countryCode?: string;
    addressStatus: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    phoneNumber?: string;
    companyName?: string;
    jobTitle?: string;
    metadata?: any;
}
```

**Comment by drbobbeaty** [comment]
@brycelund I think it's got to be a mistake on my part... let me dig into it now, and I'll update as necessary.

**Comment by drbobbeaty** [comment]
You are right - it's missing in the PostGrid docs, but not their examples, so I picked the wrong source. It's added now, and ver `0.7.0` has the field.
