### ISSUE TITLE
No way of passing idempotency key 

### ISSUE THREAD

**Issue by chrift** [flexbase-eng/postgrid-node-client#15]
The docs mention, and encourage the use of an idempotency key: https://docs.postgrid.com/?_ga=2.96519967.1223208394.1657053097-1058235818.1657052471#idempotent-requests

But there is no way of passing one to any of the calls in the SDK, from what I can tell.

Would it be possible to implement this?

**Comment by chrift** [comment]
Hey @drbobbeaty,

My personal specific need is for the letter creation endpoint, so I don't end up inadvertently sending multiple letters to the same person for the same thing. I currently have a type of idempotency key I am keeping record of for each lead, but it would be nice to be able to pass it up to postgrid too.

**Comment by drbobbeaty** [comment]
I'm planning on adding it this weekend. I'll update you as I do.

**Comment by drbobbeaty** [comment]
@chrift I've published `0.9.0` of the library, and the README has the docs on how to pass in the `idempotencyKey` to the three `create()` functions:

* Letter
* Postcard
* Check

These are the only ones that _appear_ to make sense to add this to, but you let me know how this works for you.

I'll keep the Issue open until you tell me you're in good shape. 👍

**Comment by chrift** [comment]
Cheers mate, going to implement this now.

**Comment by goodpaul6** [comment]
@drbobbeaty you're correct in assuming that the letter, postcard, and check endpoints (and the return envelope endpoints, not used in this SDK) are the ones that benefit from an idempotency key.

**Comment by drbobbeaty** [comment]
Looks like this is all closed and done.
