### ISSUE TITLE
Missing express delivery type on create functions

### ISSUE THREAD

**Issue by adamlis05** [flexbase-eng/postgrid-node-client#25]
Missing `express` delivery boolean type on `create()` methods for Letters, Checks, and Postcards.

Documentation: https://docs.postgrid.com/#express-shipping

PR: https://github.com/flexbase-eng/postgrid-node-client/pull/24

**Comment by drbobbeaty** [comment]
Published as `v0.10.0`

**Comment by drbobbeaty** [comment]
All done.
